feat: ajout d'une table de staging pour le mapping des adresses au 30/09 et la plus récente pour chaque année
CDPVD/core.dashboards_store pull request #13
Opened 2024-06-12 18:32 UTC by jalluard

# Objectives of the Pull Request ? 
Identifier l'adresse résidentielle des élèves pour chaque année. Pour chaque fiche/annee, on aura l'adresse au 30/09 et la dernière adresse

Quelques règles de construction : 
- les adresses qui débutent et se terminent le même jour ne sont pas considérées (`date_eff=date_fin`)
- Il est possible qu'un élève ait plusieurs adresses simultanément (ex: adresse mère/père). Dans ce cas-ci, on considère initialement la 1ère adresse. on l'actualise lorsque l'on a une adresse avec `ind_envoi_meq=1`

# What is left out of the Pull Request ? 
> Describe what is not included in the pull request. Why did you not include it in the PR. What are the next steps ?

# How to run the pull request ?

```bash
# Assuming you are in a folder containing both the core.data.store and the <cssXX>.data.store folder.
# Update the code
cd core.dashboards_store
git checkout feature/adding_postal_code
git pull
# Might be required if you update either the poetry file or the lock file
# poetry shell && poetry lock && poetry install 
cd ../cssvdc.dashboards_store
git checkout develop
git pull  
# Might be required if you add a new DBT dependency
# dbt deps
# Run dbt 
dbt build --select stg_adresses_eleves
```

# Checklist
> Please, read carefully each item before checking it. Your PR's review might be delayed otherwise.

* **Code** :
  * [x] The code I'm asking a review for is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x] My code follows the conventions described in the `contribution guide`.
  * [ ] My `models` / `seeds` / `adapters` are tested and documented in DBT 9through the `yaml` files.
  * I have a added a new **mandatory seed** / a new **mandatory adapter** : 
    * [ ] I have you populated the `tooling/nightly` project with my new seed / adapter.
    * [ ] An exemple of how to populate the adapter can be found in the `analysis` folder.
  * I have added a new **dashboard** : 
    * [ ] I have updated the `core.dashboards_store/tooling/template/{{ cookiecutter.css_short_name + '.dashboards_store' }}/dbt_project.yml` file with my new dashboard. 
    * [ ] I have added a new `doc` page in the `core.dashboards_store/tooling/docs/content/` appropriate folder, describing what my dashboards does and how to configure it.
    * [ ] The dashboard is saved with `.pbit` extension, **not** a `.pbix` extension, so it doesn't contains any data.
  * [ ] I have called `sqfmt .` to format my code, and **made sure my code was still running as expected after having been reformated**.
* **Documentation** : 
  * [x]  I have updated the documentation (README) accordingly to my changes.
  * [x]  The models I have added are documented in a `schema.yml` file.
* **Pull-request** : 
  * [ ]  My merge message is prefixed with a `commitizen` key word so it looks something like `<feat|fix|chore|doc|refactor|perf|style>: foo bar`**
  * [x]  The code *provided to run the pull request* is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x]  My pull request is documented. I have explained the needs for the PR, what was left out of the it and why.
  * [x]  I have carefully reviewd each changes made to a file and made sure the files included on the PR were actually added on purpose.
  * [x]  I have assignee at least **1** people to review my PR.

2024-06-12 19:18 UTC, busquef requested changes

2024-06-12 19:18 UTC, busquef commented on models/marts/educ_serv/staging/geospatial/schema.yml
> +      This is an exemple
Il manque la description de ta table ici.

2024-06-12 19:33 UTC, sadqim commented
@jalluard  il y a un fichier poetry.lock qui a été modifié. ca peut introduire des divergences avec les autres utilisateurs

2024-06-12 19:44 UTC, jalluard commented
> poetry



> @jalluard il y a un fichier poetry.lock qui a été modifié. ca peut introduire des divergences avec les autres utilisateurs

Comment je fais pour revenir au poetry d'avant. j'annule le commit?

2024-06-12 19:46 UTC, sadqim commented
> > poetry
> 
> > @jalluard il y a un fichier poetry.lock qui a été modifié. ca peut introduire des divergences avec les autres utilisateurs
> 
> Comment je fais pour revenir au poetry d'avant. j'annule le commit?

oui je pense que c'est la solution la plus simple

2024-06-13 17:51 UTC, busquef approved these changes

2024-06-13 18:15 UTC, busquef commented
![image](https://github.com/CDPVD/core.dashboards_store/assets/147734849/4338a750-4432-440e-9f9f-23e0b77869c8)
De mon bord, le tout me semble cohérent après avoir survoler et j'ai réussi à l'exécuter de mon bord. Il reste à bien sûr faire les autres tâches dans la checklist

2024-06-14 16:35 UTC, sadqim approved these changes
lgtm!

2024-06-17 13:27 UTC, merged