feat: Add new dashboard "Employees active"
CDPVD/core.dashboards_store pull request #6
Opened 2024-03-11 19:42 UTC by gabrielThiffault

# Objectives of the Pull Request ? 
Création d'un tableau de bord représentant le nombre d'employés du CSS

# What is left out of the Pull Request ? 
Rien

# How to run the pull request ?
> Provide the code required to run the pull request. This is the code that will be used to review your pull request. **The provided code must work as-is. If a DBT error is raised while running the code, the PR will be rejected. The following code / placeholder is only provided as documentation / helper to get you started and you will need to adjust it.**

```bash
# Assuming you are in a folder containing both the core.data.store and the <cssXX>.data.store folder.
# Update the code
cd core.dashboards_store
git checkout feature/feature/rh_emp_actif
git pull
# Might be required if you update either the poetry file or the lock file
# poetry shell && poetry lock && poetry install 
cd ../<cssXX>.dashboards_store
git checkout feature/feature/rh_emp_actif
git pull  
# Might be required if you add a new DBT dependency
# dbt deps
# Run dbt 
dbt build --select +tag:emp_actif
```

# Checklist
> Please, read carefully each item before checking it. Your PR's review might be delayed otherwise.

* **Code** :
  * [X] The code I'm asking a review for is working. **I understand that my PR will be rejected as-is otherwise.**
  * [X] My code follows the conventions described in the `contribution guide`.
  * [X] My `models` / `seeds` / `adapters` are tested and documented in DBT 9through the `yaml` files.
  * I have a added a new **mandatory seed** / a new **mandatory adapter** : 
    * [] I have you populated the `tooling/nightly` project with my new seed / adapter.
    * [] An exemple of how to populate the adapter can be found in the `analysis` folder.
  * I have added a new **dashboard** : 
    * [X] I have updated the `core.dashboards_store/tooling/template/{{ cookiecutter.css_short_name + '.dashboards_store' }}/dbt_project.yml` file with my new dashboard. 
    * [] I have added a new `doc` page in the `core.dashboards_store/tooling/docs/content/` appropriate folder, describing what my dashboards does and how to configure it.
    * [x] The dashboard is saved with `.pbit` extension, **not** a `.pbix` extension, so it doesn't contains any data.
  * [X] I have called `sqfmt .` to format my code, and **made sure my code was still running as expected after having been reformated**.
* **Documentation** : 
  * [ ]  I have updated the documentation (README) accordingly to my changes.
  * [X]  The models I have added are documented in a `schema.yml` file.
* **Pull-request** : 
  * [x]  My merge message is prefixed with a `commitizen` key word so it looks something like `<feat|fix|chore|doc|refactor|perf|style>: foo bar`**
  * [X]  The code *provided to run the pull request* is working. **I understand that my PR will be rejected as-is otherwise.**
  * [X]  My pull request is documented. I have explained the needs for the PR, what was left out of the it and why.
  * [X]  I have carefully reviewd each changes made to a file and made sure the files included on the PR were actually added on purpose.
  * [X]  I have assignee at least **1** people to review my PR.

2024-03-14 12:38 UTC, sadqim commented
@gabrielThiffault le permettant de rouler la PR ne fonctionne pas! peux tu revoir ce qui ne fonctionne pas stp

2024-03-14 12:39 UTC, sadqim requested changes
Compilation Error
  Model 'model.cssvt_tbe.dim_mapper_workplace' (models/marts/human_resources/dimensions/dim_mapper_workplace.sql) depends on a node named 'i_pai_tab_lieu_trav' which is disabled

2024-03-14 15:52 UTC, gabrielThiffault commented
> rouler



> Compilation Error Model 'model.cssvt_tbe.dim_mapper_workplace' (models/marts/human_resources/dimensions/dim_mapper_workplace.sql) depends on a node named 'i_pai_tab_lieu_trav' which is disabled

Si possible de réessayer, svp

2024-03-14 17:13 UTC, sadqim commented
@gabrielThiffault  ca ne fonctionne toujours pas! 
![image](https://github.com/CDPVD/core.dashboards_store/assets/146247957/b435096f-19bf-4348-9e67-fbd9987329d3)

je sais pas si c'est la cause mais ton package ne pointe pas vers le bon répertoire
![image](https://github.com/CDPVD/core.dashboards_store/assets/146247957/0b9b0b7a-abb7-4032-bf17-2c2971c82069)

2024-03-14 17:45 UTC, sadqim commented
> > @gabrielThiffault ca ne fonctionne toujours pas! ![image](https://private-user-images.githubusercontent.com/146247957/312933618-b435096f-19bf-4348-9e67-fbd9987329d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzY2ODUsIm5iZiI6MTcxMDQzNjM4NSwicGF0aCI6Ii8xNDYyNDc5NTcvMzEyOTMzNjE4LWI0MzUwOTZmLTE5YmYtNDM0OC05ZTY3LWZiZDk5ODczMjlkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNzEzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWNiNTBiN2VjNWE2YTNmNzRlYTc5MGU0ZjIxYzk0MmVjNzgyY2Q2ZDA4ZWM2ZDkzMTU1NWU1YjVmZTQ2ZjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0UprHYsIK8WwbyzssFvRNREPWe1ZUyYrW3su6CI_6Ag)
> > je sais pas si c'est la cause mais ton package ne pointe pas vers le bon répertoire ![image](https://private-user-images.githubusercontent.com/146247957/312933857-0b9b0b7a-abb7-4032-bf17-2c2971c82069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzY2ODUsIm5iZiI6MTcxMDQzNjM4NSwicGF0aCI6Ii8xNDYyNDc5NTcvMzEyOTMzODU3LTBiOWIwYjdhLWFiYjctNDAzMi1iZjE3LTJjMjk3MWM4MjA2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNzEzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODllZmMyZDhhMjNmNmIzYzFmY2QzYzdiZDAzODM3YmEzYjk2NGQ1NzI3MjZjOTE1NmQ2MDUxMmM1OGFmMTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cxgpNTHQ5v-df7oJDLIlTbc2DtILuTTI2lJyZ7EYkTY)
> 
> My bad, changement apporté

il vaut mieux nommé le répertoire core "core.dashboards_store" pour que ca fonctionne pour tout le monde

2024-03-14 18:55 UTC, sadqim commented
> > > > @gabrielThiffault ca ne fonctionne toujours pas! ![image](https://private-user-images.githubusercontent.com/146247957/312933618-b435096f-19bf-4348-9e67-fbd9987329d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzY2ODUsIm5iZiI6MTcxMDQzNjM4NSwicGF0aCI6Ii8xNDYyNDc5NTcvMzEyOTMzNjE4LWI0MzUwOTZmLTE5YmYtNDM0OC05ZTY3LWZiZDk5ODczMjlkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNzEzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWNiNTBiN2VjNWE2YTNmNzRlYTc5MGU0ZjIxYzk0MmVjNzgyY2Q2ZDA4ZWM2ZDkzMTU1NWU1YjVmZTQ2ZjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0UprHYsIK8WwbyzssFvRNREPWe1ZUyYrW3su6CI_6Ag)
> > > > je sais pas si c'est la cause mais ton package ne pointe pas vers le bon répertoire ![image](https://private-user-images.githubusercontent.com/146247957/312933857-0b9b0b7a-abb7-4032-bf17-2c2971c82069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzY2ODUsIm5iZiI6MTcxMDQzNjM4NSwicGF0aCI6Ii8xNDYyNDc5NTcvMzEyOTMzODU3LTBiOWIwYjdhLWFiYjctNDAzMi1iZjE3LTJjMjk3MWM4MjA2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNzEzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODllZmMyZDhhMjNmNmIzYzFmY2QzYzdiZDAzODM3YmEzYjk2NGQ1NzI3MjZjOTE1NmQ2MDUxMmM1OGFmMTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cxgpNTHQ5v-df7oJDLIlTbc2DtILuTTI2lJyZ7EYkTY)
> > > 
> > > 
> > > My bad, changement apporté
> > 
> > 
> > il vaut mieux nommé le répertoire core "core.dashboards_store" pour que ca fonctionne pour tout le monde
> 
> Le nom du core a été changé dans le package.yml.
> 
> Mais avant ce changement, tout fonctionnait :
> 
> ![image](https://private-user-images.githubusercontent.com/147753578/312954725-077646af-3fed-4e29-ba0f-104f69d43011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDA5NjYsIm5iZiI6MTcxMDQ0MDY2NiwicGF0aCI6Ii8xNDc3NTM1NzgvMzEyOTU0NzI1LTA3NzY0NmFmLTNmZWQtNGUyOS1iYTBmLTEwNGY2OWQ0MzAxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxODI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGVlMDAxYjVhY2ZjZGY1NDkyN2VkMmI3N2Y0NDE3ODBmMWE2MDE3YTE3ODFmODUwNGY2OGNmYzM1M2RiOTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vqotjbb5vh5LbNxPAmByjkeshBpqZMc9YTway_2Zfek)

oui pour toi elle va rouler mais pour les autres qui vont rouler la PR sur ton répertoire cssvt il vont devoir faire un dbt deps(pour ca il faut que le package ait le même nom partout)

2024-03-26 13:22 UTC, sadqimo commented on models/marts/human_resources/spines/spine_rh.sql
> +{#
@gabrielThiffault à quoi sert cette table? elle n'est pas utiliser dans ce tdb?

2024-03-26 13:25 UTC, sadqimo commented on models/marts/human_resources/features/schema.yml
> +  - name: fact_tps_partial
@gabrielThiffault, je ne vois pas cette table. est ce qu'elle existe encore ?

2024-03-26 13:28 UTC, sadqimo commented on models/marts/human_resources/features/schema.yml
> +            - year_check
@gabrielThiffault il faut mettre a jour les schema.yml

2024-03-26 13:28 UTC, sadqimo commented on models/marts/human_resources/features/active/schema.yml
> +        description: The unique identifier of an employee.
@gabrielThiffault même commentaire, il faut le metre à jour le schema.yml

2024-03-26 15:07 UTC, sadqimo commented on models/marts/human_resources/features/activity/fact_activity_current.sql
>  where last_pay_date > dateadd(week, -2, getdate())  -- Make sure the activte employes have been paid in the last two weeks
@gabrielThiffault je suis curieux :), est ce que tu as pu verifé si la volumétrie de cette table correspond à votre nombre total d'employés

2024-03-26 15:17 UTC, sadqimo commented
@gabrielThiffault, peux tu m'explique stp la différence entre la table " emp_actif_fact_base", la "fact_activity_current" et la "fact_today_active"

2024-03-26 16:01 UTC, sadqimo commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +left join {{ ref("dim_employees") }} as emp on act.matr = emp.matr
@gabrielThiffault pour les joins ... est ce que tu es sur que c'est des left et non des inner ?

2024-03-26 18:16 UTC, gabrielThiffault commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +left join {{ ref("dim_employees") }} as emp on act.matr = emp.matr
Ça sort le même nombre d'employés, mais oui t'as raison

2024-03-26 18:16 UTC, gabrielThiffault commented on models/marts/human_resources/features/activity/fact_activity_current.sql
>  where last_pay_date > dateadd(week, -2, getdate())  -- Make sure the activte employes have been paid in the last two weeks
Oui, sans les règles d'affaires nous arrivons à 2269 et le script lui donne 2231

2024-03-26 18:19 UTC, gabrielThiffault commented on models/marts/human_resources/features/schema.yml
> +  - name: fact_tps_partial
Nope

2024-03-26 18:26 UTC, gabrielThiffault commented on models/marts/human_resources/features/schema.yml
> +            - year_check
Retiré

2024-03-26 19:23 UTC, gabrielThiffault commented on models/marts/human_resources/features/active/schema.yml
> +        description: The unique identifier of an employee.
Retiré

2024-03-26 19:30 UTC, sadqimo commented
> Ça sort le même nombre d'employés, mais oui t'as raison 

je crois qu'il faut utiliser des inner dans ce cas

2024-03-26 19:30 UTC, sadqimo commented
> Oui, sans les règles d'affaires nous arrivons à 2269 et le script lui donne 2231 

les RH de votre coté sont correcte avec ce chiffre ?

2024-03-26 19:34 UTC, gabrielThiffault commented
> @gabrielThiffault, peux tu m'explique stp la différence entre la table " emp_actif_fact_base", la "fact_activity_current" et la "fact_today_active"

1. fact_activity_current: retiré
2. fact_activity_current : Donne uniquement  les employés actuellement actifs "where last_pay_date > dateadd(week, -2, getdate())"
3. emp_actif_fact_base : Permet de joindre les deux, employés actuellement actifs et actif

2024-03-26 19:35 UTC, gabrielThiffault commented
> > Oui, sans les règles d'affaires nous arrivons à 2269 et le script lui donne 2231
> 
> les RH de votre coté sont correcte avec ce chiffre ?

Oui

2024-04-02 12:05 UTC, sadqimo commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +    act.type as 'asdf34',
@gabrielThiffault, ca veut dire quoi asdf34 ?

2024-04-02 12:09 UTC, sadqimo commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +    emp.sex as gender,
@gabrielThiffault à mofier suivant les modifications du nom de la colonne dans la table dim_employees

2024-04-02 12:17 UTC, sadqimo commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +left join {{ ref("dim_mapper_workplace") }} lieu on act.workplace = lieu.workplace
@gabrielThiffault est ce qu'on peut remplacer les left join par des inner? (c'est une question dont je comnnais pas la réponse :) )

2024-04-02 12:58 UTC, sadqim commented
@gabrielThiffault suggestion : ajouter les étiquettes de données
![Capture d’écran 2024-04-02 085216](https://github.com/CDPVD/core.dashboards_store/assets/146247957/cdcad94d-9fba-48fa-aae1-a475e184e506)

2024-04-02 13:10 UTC, sadqim commented
@gabrielThiffault est ce que ca correspond au nombre d'employés ? si oui il serait mieux de le mettre dans un encadrer avec un titre  
![image](https://github.com/CDPVD/core.dashboards_store/assets/146247957/bf3104cb-a5dd-4019-8478-fa31ab0b90dd)

2024-04-02 13:13 UTC, sadqim commented
@gabrielThiffault  autre suggestion mettre une place dans le tdb powerbi pour mettre un lien vers le rapport reportbuilder. pour que chacun insert le lien quand il aura publier le tdb

2024-04-04 17:17 UTC, gabrielThiffault commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +    act.type as 'asdf34',
Fichue de bonne question :), probablement des tests. Il a été supprimé

2024-04-04 17:17 UTC, gabrielThiffault commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +    end as 'renumeration_mode',
De mémoire, oui, je me renseigne demain auprès de Mélanie.

2024-04-04 17:48 UTC, gabrielThiffault commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +left join {{ ref("dim_mapper_workplace") }} lieu on act.workplace = lieu.workplace
Pour les lefts join présents, ont ne peut pas les remplacer par des inner join

2024-04-05 14:55 UTC, gabrielThiffault commented on models/dashboards/emp_actif/features/emp_actif_fact_emp_actif.sql
> +    end as 'renumeration_mode',
**Le mode de rémunération est régi par les ententes nationales donc tous les CSS doivent suivre le mode.

2024-04-09 17:44 UTC, gabrielThiffault commented
**Tableau report builder mis à jour :** 
1. L'impression fonctionne sans saut de page inutile. Pour y arriver, nous avons dû retirer la colonne "Adresse courriel"
2. L'en-tête s'affiche maintenant sur toutes les pages

2024-04-12 18:49 UTC, sadqim commented
@gabrielThiffault , possible d'agrandir les plages des paramètres 
![image](https://github.com/CDPVD/core.dashboards_store/assets/146247957/2ee8150e-40fb-44f0-96eb-da9c82a4c804)

2024-04-18 17:18 UTC, gabrielThiffault commented
> @gabrielThiffault , possible d'agrandir les plages des paramètres ![image](https://private-user-images.githubusercontent.com/146247957/322101470-2ee8150e-40fb-44f0-96eb-da9c82a4c804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NjAyOTQsIm5iZiI6MTcxMzQ1OTk5NCwicGF0aCI6Ii8xNDYyNDc5NTcvMzIyMTAxNDcwLTJlZTgxNTBlLTQwZmItNDRmMC05NmViLWRhOWM4MmE0YzgwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxNzA2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWY4YTJkYjQzNzg4NDI4NWI4ZWNmNWIzNzZhZjhhMDk2ZDhhOGMyYTJkYmY0NWJlM2FiYzk5YzAzNTk4OWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vwSAZVwfcKufLnSBzT3h4J2HZbcn09VPZn07iAGAuJs)

Non ce n'est pas possible, j'ai regardé avec Fred et nous n'avons rien trouvé

2024-04-22 15:01 UTC, sadqim approved these changes
LGTM

2024-04-22 15:53 UTC, jalluard commented
Il y a 2 coquilles dans ta section "" : 
- Remplacer `cd ../<cssXX>.dashboards_store` par `cd ../<cssXX>.data.tbe`
- Remplacer `git checkout feature/feature/rh_emp_actif` par `git checkout feature/rh_emp_actif`

2024-04-22 18:21 UTC, jalluard commented on models/marts/human_resources/features/activity/fact_activity_current.sql
>  where last_pay_date > dateadd(week, -2, getdate())  -- Make sure the activte employes have been paid in the last two weeks
Mettre le prefixe dme avant last_pay_date

2024-04-22 18:23 UTC, jalluard commented on models/marts/human_resources/features/schema.yml
> +
Souci ici non?

2024-04-22 18:42 UTC, jalluard requested changes
juste corriger les choses mentionnées dans mes 2 commentaires. Belle PR ;)

2024-04-26 12:46 UTC, sadqim commented
allo @gabrielThiffault est ce que c'est réglé ?

2024-05-06 12:58 UTC, sadqim commented
> allo @gabrielThiffault est ce que c'est réglé ?

Salut @gabrielThiffault est ce qu'il y a bloquant de ton coté ?

2024-05-07 13:45 UTC, gabrielThiffault commented on models/marts/human_resources/features/schema.yml
> +
Effectivement, il y a avait de l'information qui se contredisait

2024-05-07 18:04 UTC, sadqim approved these changes

2024-05-07 18:10 UTC, jalluard approved these changes

2024-05-08 16:46 UTC, merged